###
###     MCEssentials Main Configuration
###
### Please visit the 'lang' and 'feature' folders for more configurations
basic:
  prefix: "&7&l[&3&lMCE&b&lssentials&7&l] "

### Current Values you can set:
## CURRENT LANGUAGES SUPPORTED : lang_en (English) | lang_es (Spanish) | lang_ru (Russian)
## lang_it (Italian) | lang_de (german) | lang_nl (dutch)
language: "lang_en" # default language