#Please visit the /lang folder to adjust the messages
#Visit the /features folder to adjust each Feature MCEssentials has


#Current Values you can set:
# lang_en ; lang_es ; lang_ru
language: "lang_en" # default language

#Can set this by standing and typing /mce setfirstspawn
firstTimeSpawn:
  handleFirstSpawn: false
  x: 1
  y: 1
  z: 1

Use-Essentials-For-Spawn: false

#Do you want MCEssentials to route players who type /spawn to this location?
#Can set this by standing and typing /mce setspawn
spawn:
  world: world
  x: 0
  y: 0
  z: 0
  pitch: 0
  yaw: 0