name: MCEssentials
version: '${project.version}'
main: com.findzach.mcessentials.MCEssentials
softdepend: [PlaceholderAPI, Vault]
commands:
  gmc:
    description: Change Gamemode to Creative
    usage: /<command>
    permission: essentials.gamemode.creative
  gms:
    description: Change Gamemode to Survival
    usage: /<command>
    permission: essentials.gamemode.survival
  gma:
    description: Change Gamemode to Adventure
    usage: /<command>
    permission: essentials.gamemode.adventure
  gmspec:
    description: Change Gamemode to Spectator
    usage: /<command>
    permission: essentials.gamemode.spectator
  ping:
    description: Ping command
    usage: /<command>
    permission: essentials.ping
  day:
    description: Changes the time to Day
    usage: /<command>
    permission: essentials.day
  night:
    description: Changes the time to night
    usage: /<command>
    permission: essentials.night
  fly:
    description: Toggles fly for user
    usage: /<command>
    permission: essentials.fly
  mce:
    description: Essentials base command
    aliases:
      - essentials
      - essential
    usage: /<command>
    permission: essentials.mce
  heal:
    description: Heal command
    usage: /<command>
    permission: essentials.heal
  feed:
    description: Feed command
    usage: /<command>
    permission: essentials.feed
  feature:
    description: Feature command
    usage: /<command>
    permission: essentials.feature
  spawn:
    description: spawn command
    usage: /<command>
    permission: essentials.spawn
  setspawn:
    description: Set spawn command
    usage: /<command>
    permission: essentials.setspawn
  vanish:
    description: User Vanish Command
    usage: /<command>
    permission: essentials.mod.vanish
  balance:
    description: User Vanish Command
    aliases:
      - bal
      - money
    usage: /<command>
    permission: essentials.mod.vanish
  pay:
    description: Economy Pay Command
    usage: /<command>
    permission: essentials.eco.pay